# Generated by Django 5.0.3 on 2024-04-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_avatar_remove_question_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/catty.jpg', null=True, upload_to=''),
        ),
    ]
