# Generated by Django 5.0.3 on 2024-04-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answersmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswersManager',
        ),
    ]
