# Generated by Django 5.0.3 on 2024-04-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_likeanswer_likequestion_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answers'),
        ),
        migrations.AlterField(
            model_name='likequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('profile', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('profile', 'question')},
        ),
    ]
